# Generated by Django 4.2.2 on 2023-09-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=50)),
                ("serial_num", models.CharField(blank=True, max_length=50)),
                ("maker", models.CharField(max_length=50)),
                ("notes", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
