# Generated by Django 4.2.2 on 2023-09-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("address", models.CharField(blank=True, max_length=50)),
                ("city", models.CharField(blank=True, max_length=50)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("zip", models.IntegerField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("notes", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
